items:
  チーゴのみ: chigonomi
  どくばり: dokubari
  ひかりのこな: hikarinokona
  じしゃく: jisyaku
  カゴのみ: kagonomi
  かいがらのすず: kaigaranosuzu
  カムラのみ: kamuranomi
  きあいのハチマキ: kiainohachimaki
  きちょうなほね: kityounahone
  キーのみ: kinomi
  きせきのたね: kisekinotane
  こだわりハチマキ: kodawarihachimaki
  クラボのみ: kurabonomi
  くろおび: kuroobi
  くろいメガネ: kuroimegane
  まがったスプーン: magattasupunn
  メンタルハーブ: mentaruhabu
  もくたん: mokutann
  モモンのみ: momonnnomi
  のんきのおこう: nonnkinookou
  オボンのみ: obonnnomi
  おうじゃのしるし: oujyanosirusi
  ピントレンズ: pinntorennzu
  ラムのみ: ramunomi
  せんせいのツメ: sennseinotume
  しんぴのしずく: sinnpinosizuku
  しろいハーブ: siroihabu
  するどいくちばし: surudoikutibasi
  たべのこし: tabenokosi
  チイラのみ: tiiranomi
  とけないこおり: tokenaikoori
  ヤタピのみ: yatapinomi
  やわらかいすな: yawarakaisuna
