items:
  あく: aku
  チーゴのみ: chi-gonomi
  ちからのハチマキ: chikaranohachimaki
  どくばり: dokubari
  フィラのみ: firanomi
  ひかりのこな: hikarinokona
  じしゃく: jisyaku
  カゴのみ: kagonomi
  かいがらのすず: kaigaranosuzu
  カムラのみ: kamuranomi
  きあいのハチマキ: kiainohachimaki
  きちょうなほね: kityounahone
  きせきのたね: kisekinotane
  クラボのみ: kurabonomi
  まがったスプーン: magattasupu-nn
  もくたん: mokutann
  オボンのみ: obonnnomi
  おうじゃのしるし: oujyanosirusi
  ピントレンズ: pinntorennzu
  ラムのみ: ramunomi
  せんせいのツメ: sennseinotume
  しんぴのしずく: sinnpinosizuku
  しろいハーブ: siroiha-bu
  するどいくちばし: surudoikutibasi
  たべのこし: tabenokosi
  チイラのみ: chiiranomi
  とけないこおり: tokenaikoori
