names:
  アーボック: aboku
  アブソル: abusoru
  アゲハント: agehannto
  アーマルド: amarudo
  アメモース: amemosu
  アンノーン: annon
  アノプス: anopusu
  アリアドス: ariadosu
  アリゲイツ: arigeitu
  アズマオウ: azumaou
  バクーダ: bakuda
  バクフーン: bakufunn
  バクオング: bakuonngu
  バネブー: banebu
  バンギラス: banngirasu
  バリヤード: bariyado
  バルビート: barubito
  バシャーモ: basyamo
  バタフリー: batafuri
  ベイリーフ: beirifu
  ベロリンガ: berorinnga
  ベトベター: betobeta
  ベトベトン: betobetonn
  ビブラーバ: biburaba
  ビリリダマ: biriridama
  ボーマンダ: bomannda
  ボスゴドラ: bosugodora
  ブーバー: buba
  ブビィ: bubyi
  ブーピッグ: bupiggu
  ブラッキー: burakki
  ブースター: busuta
  ダグトリオ: dagutorio
  ダーテング: datenngu
  デンリュウ: dennryu
  デリバード: deribado
  デルビル: derubiru
  ドードリオ: dodorio
  ドガース: dogasu
  ドゴーム: dogomu
  ドクケイル: dokukeiru
  ドククラゲ: dokukurage
  ドンファン: donnfann
  エアームド: eamudo
  エビワラー: ebiwara
  エーフィ: efi
  エイパム: eipamu
  エネコロロ: enekororo
  エンテイ: enntei
  エレブー: erebu
  エレキッド: erekiddo
  ファイヤー: faiya
  フォレトス: foretosu
  フーディン: fudhinn
  フライゴン: furaigonn
  フリーザー: furiza
  フシギバナ: fusigibana
  フシギソウ: fusigisou
  ガーディ: gadhi
  ガラガラ: garagara
  ガルーラ: garura
  ゲンガー: gennga
  ゴマゾウ: gomazou
  ゴーリキー: goriki
  ごローン: goronn
  ゴローニャ: goronya
  ゴルバット: gorubatto
  ゴルダック: gorudakku
  ゴースト: gosuto
  グラエナ: guraena
  グライガー: guraiga
  グランブル: gurannburu
  ギャラドス: gyaradosu
  ギャロップ: gyaroppu
  ハブネーク: habuneku
  ハゲネール: haganeru
  ハクリュー: hakuryu
  ハンテール: hannteru
  ハピナス: hapinasu
  ハリーセン: harisenn
  ハリテヤマ: hariteyama
  ハッサム: hassamu
  ハスブレロ: hasuburero
  ヘラクロス: herakurosu
  ヘルガー: heruga
  ヒメグマ: himeguma
  ヒトデマン: hitodemann
  ホエルコ: hoeruko
  ホエルオー: hoeruo
  イーブイ: ibui
  イノムー: inomu
  イルミーゼ: irumize
  イワーク: iwaku
  ジーランス: jirannsu
  ジュゴン: jyugonn
  ジュカイン: jyukainn
  ジュペッタ: jyupetta
  ジュプトル: jyuputoru
  カビゴン: kabigonn
  カブト: kabuto
  カブトプス: kabutopusu
  カイリキー: kairiki
  カイロス: kairosu
  カイリュー: kairyu
  カクレオン: kakureonn
  カメックス: kamekkusu
  カメール: kameru
  カモネギ: kamonegi
  カポエラー: kapoera
  ケッキング: kekkinnguu
  ケンタロス: kenntarosu
  キマワリ: kimawari
  キングドラ: kinngudora
  キングラー: kinngura
  キノガッサ: kinogassa
  キレイハナ: kireihana
  キリンリキ: kirinnriki
  ココドラ: kokodora
  コモルー: komoru
  コノハナ: konohana
  コータス: kotasu
  クラブ: kurabu
  クロバット: kurobatto
  クサイハナ: kusaihana
  クチート: kutito
  キュウコン: kyuukonn
  マグカルゴ: magukarugo
  マグマラシ: magukmarasi
  マイナン: mainann
  マンタイン: manntainn
  マリルリ: mariruri
  マルマイン: marumainn
  マルノーム: marunomu
  マッスグマ: massuguma
  マタドガス: matadogasu
  メガニウム: meganiumu
  メノクラゲ: menokurage
  メタグロス: metagurosu
  メタング: metanngu
  ミロカロス: mirokarosu
  ミルタンク: mirutannku
  モココ: mokoko
  モンジャラ: monnjyara
  モルフォン: morufonn
  ムウマ: muuma
  ナマズン: namazunn
  ナッシー: nassi
  ネイティオ: neithio
  ネンドール: nenndoru
  ニドキング: nidokinngu
  ニドクイン: nidokuinn
  ニドリーナ: nidorina
  ニドリーノ: nidorino
  ノコッチ: nokotti
  ノクタス: nokutasu
  ノズパス: nozupasu
  ヌマクロー: numakuro
  ヌオー: nuo
  ニョロボン: nyorobonn
  ニョロトノ: nyorotono
  ニョロゾ: nyorozo
  ニューラ: nyura
  オーダイル: odairu
  オドシシ: odosisi
  オコリザル: okorizaru
  オクタン: okutann
  オムナイト: omunaito
  オムスター: omusuta
  オニドリル: onidoriru
  オニゴーリ: onigori
  オオスバメ: oosubame
  オオタチ: ootati
  パラセクト: parasekuto
  パールル: paruru
  パルシェン: parusyenn
  パッチール: pattiru
  ペリッパー: perippa
  ペルシアン: perusiann
  ピジョン: pijyonn
  ピジョット: pijyotto
  ピクシー: pikusi
  ポニータ: ponita
  ポポッコ: popoko
  ポリゴン: porigonn
  ポリゴン2: porigonn2
  ポワルン: powarunn
  プクリン: pukurinn
  プラスル: purasuru
  プテラ: putera
  ラブカス: rabukasu
  ラフレシア: rafuresia
  ラグラージ: raguraji
  ライボルト: raiboruto
  ライコウ: raikou
  ライチュウ: raityuu
  ラッキー: rakki
  ランターン: ranntann
  ラプラス: rapurasu
  ラティアス: rathiasu
  ラティオス: rathiosu
  ラッタ: ratta
  レアコイル: reakoiru
  レディアン: redhiann
  レジアイス: rejiaisu
  レジロック: rejirokku
  レジスチル: rejisutiru
  リングマ: rinnguma
  リリーラ: ririra
  リザード: rizado
  リザードン: rizadonn
  ロゼリア: rozeria
  ルージュラ: rujyura
  ルナトーン: runatonn
  ルンパッパ: runnpappa
  サボネア: sabonnea
  サイドン: saidonn
  サイホーン: saihonn
  サクラビス: sakurabisu
  サマヨール: samayoru
  サメハダー: samehada
  サーナイト: sanaito
  サニーゴ: sanigo
  サナギラス: sannagerasu
  サンダー: sannda
  サンダース: sanndasu
  サンドパン: sanndopann
  サワムラー: sawamura
  シードラ: sidora
  シザリガー: sizariga
  ソーナンス: sonannsu
  ソルロック: sorurokku
  スイクン: suikunn
  スリーパー: suripa
  スターミー: sutami
  ストライク: sutoraiku
  シャワーズ: syawazu
  タマタマ: tamatama
  テッカニン: tekkaninn
  チリーン: tirinn
  チルタリス: tirutarisu
  トドグラー: todogura
  トドゼルガ: todozeruga
  トゲチック: togetikku
  トロピウス: toropiusu
  ツボツボ: tubotubo
  チャーレム: tyaremu
  チョンチー: tyonnti
  ウインディ: uinndhi
  ウソッキー: usokki
  ウツボット: utubotto
  ウツドン: utudonn
  ワカシャモ: wakasyamo
  ワタッコ: watakko
  ヤドキング: yadokinngu
  ヤドラン: yadorann
  ヤミカラス: yamikarasu
  ヤミラミ: yamirami
  ヤンヤンマ: yannyannma
  ヤルキモノ: yarukimono
  ヨルノズク: yorunozuku
  ユンゲラー: yunngera
  ユレイドル: yureidoru
  ザングース: zanngusu
