types:
  あく: aku
  でんき: dennki
  どく: doku
  ドラゴン: doragonn
  エスパー: esupa
  ゴースト: gosuto
  はがね: hagane
  ひこう: hikou
  ほのお: honoo
  いわ: iwa
  じめん: jimenn
  かくとう: kakutou
  こおり: koori
  くさ: kusa
  みず: mizu
  むし: musi
  ノーマル: nomaru
