module Pawapuro::AbilitiesHelper
  def common_special_abilities
    [
      { id: "tubamekiller", label: "ツバメキラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "yokohamakiller", label: "横浜キラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "hannsinnkiller", label: "阪神キラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kyojinnkiller", label: "巨人キラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "hirosimakiller", label: "広島キラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "tyuunitikiller", label: "中日キラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "orixkiller", label: "オリックスキラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "hawkskiller", label: "ホークスキラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "leokiller", label: "レオキラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "rakutennkiller", label: "楽天キラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "lottekiller", label: "ロッテキラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "nipponhamukiller", label: "日本ハムキラー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kokusaitaikaimaru", label: "国際大会〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kokusaitaikaibatu", label: "国際大会✕", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" }
    ]
  end

  def pitcher_special_abilities
    [
      { id: "kire", label: "キレ〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kyouinokireaji", label: "驚異の切れ味", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "jairoboru", label: "ジャイロボール", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "haisupinnjairo", label: "ハイスピンジャイロ", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "omoitama", label: "重い球", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "karuitama", label: "軽い球", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "kaibutukyuui", label: "怪物球威", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "nigedama", label: "逃げ球", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "ippatu", label: "一発", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "honnruidagennkinn", label: "本塁打厳禁", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "giatyennji", label: "ギアチェンジ", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "siriagari", label: "尻上がり", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "syuubannryoku", label: "終盤力", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "datusannsinn", label: "奪三振", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "doctor-k", label: "ドクターK", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "kennsei", label: "牽制〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "release", label: "リリース〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "dakyuuhannnou", label: "打球反応〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "katiunn", label: "勝ち運", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "makeunn", label: "負け運", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "syourinohosi", label: "勝利の星", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "tousi", label: "闘志", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "toukonn", label: "闘魂", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "iatukanntousyu", label: "威圧感(投手)", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "konnjyou", label: "根性〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "dokonnjyou", label: "ド根性", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "crossfire", label: "クロスファイヤー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "crosscannon", label: "クロスキャノン", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "tamamoti", label: "球持ち〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "delayedarm", label: "ディレイドアーム", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "hikume", label: "低め〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "seimitukikai", label: "精密機械", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "kannkyuu", label: "緩急〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "henngennjizai", label: "変幻自在", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "taikyoudasya", label: "対強打者〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "syuhoukiller", label: "主砲キラー", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "kinnkyuutoubann", label: "緊急登板〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kyuusokuanntei", label: "球速安定", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "naikakuzeme", label: "内角攻め", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "naikakumusou", label: "内角無双", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "kaimatagi", label: "回またぎ〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "toudayakudou", label: "投打躍動", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "tyoutoudayakudou", label: "超投打躍動", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "flyballpitcher", label: "フライボールピッチャー", css_class: "pawa-checkbox-gb", text_class: "pawa-text-good-bad" },
      { id: "goropitcher", label: "ゴロピッチャー", css_class: "pawa-checkbox-gb", text_class: "pawa-text-good-bad" },
      { id: "pokerface", label: "ポーカーフェイス", css_class: "pawa-checkbox-gb", text_class: "pawa-text-good-bad" },
      { id: "naturalshoot", label: "ナチュラルシュート", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "shootkaitenn", label: "シュート回転", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "sunnzenn", label: "寸前✕", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "aredama", label: "荒れ球", css_class: "pawa-checkbox-gb", text_class: "pawa-text-good-bad" },
      { id: "abaredama", label: "暴れ球", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "sikyuu", label: "四球", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "zennkai", label: "全開", css_class: "pawa-checkbox-gb", text_class: "pawa-text-good-bad" },
      { id: "kannzennnennsyou", label: "完全燃焼", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "tairannermaru", label: "対ランナー〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "tairannerbatu", label: "対ランナー✕", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "tatiagari", label: "立ち上がり〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "slowstarter", label: "スロースターター", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "topgear", label: "トップギア", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "tannki", label: "短気", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "tikarahaibunn", label: "力配分", css_class: "pawa-checkbox-gb", text_class: "pawa-text-good-bad" },
      { id: "massura", label: "真っスラ", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "yousyo", label: "要所〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "ranntyou", label: "乱調", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" }
    ]
  end

  def fielder_special_abilities
    [
      { id: "sasayakisennjyutu", label: "ささやき戦術", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "bazookasoukyuu", label: "バズーカ送球", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "averagehitter", label: "アベレージヒッター", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "anndaseizouki", label: "安打製造機", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "powerhitter", label: "パワーヒッター", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "artist", label: "アーチスト", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "linedrive", label: "ラインドライブ", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "koukakudahou", label: "広角打法", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "koukakuhou", label: "広角砲", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "pullhitter", label: "プルヒッター", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "hippariya", label: "引っ張り屋", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "nagasiuti", label: "流し打ち", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "geijyututekinagasiuti", label: "芸術的流し打ち", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "katameuti", label: "固め打ち", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "mettauti", label: "メッタ打ち", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "nebariuti", label: "粘り打ち", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "sannsinn", label: "三振", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "sennpuuki", label: "扇風機", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "bunt", label: "バント〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "buntsyokuninn", label: "バント職人", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "naiyaannda", label: "内野安打〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "rocketstart", label: "ロケットスタート", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "syokyuu", label: "初球〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "ikkyuunyuukonn", label: "一球入魂", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "chancemaker", label: "チャンスメーカー", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kirikomitaityou", label: "切り込み隊長", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "gyakkyou", label: "逆境〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kajibanobakajikara", label: "火事場の馬鹿力", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "daida", label: "代打〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "daidanokamisama", label: "代打の神様", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "highballhitter", label: "ハイボールヒッター", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "koukyuuhituda", label: "高球必打", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "lowballhitter", label: "ローボールヒッター", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "teikyuuhituda", label: "低球必打", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "ibusiginn", label: "いぶし銀", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "syubisyokuninn", label: "守備職人", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "majyutusi", label: "魔術師", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "moodmaru", label: "ムード〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "moodbatu", label: "ムード✕", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "seisinntekisityuu", label: "精神的支柱", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "igaisei", label: "意外性", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "oobannkuruwase", label: "大番狂わせ", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "taiace", label: "対エース〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "acekiller", label: "エースキラー", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "hometotunyuu", label: "ホーム突入", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "jyuusennsya", label: "重戦車", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "pressurerun", label: "プレッシャーラン", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kakurann", label: "かく乱", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "trickstar", label: "トリックスター", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "incoursehitter", label: "インコースヒッター", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "naikakuhituda", label: "内角必打", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "outcoursehitter", label: "アウトコースヒッター", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "gaikakuhituda", label: "外角必打", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "taihennkakyuu", label: "対変化球〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "dameosi", label: "ダメ押し", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "iatukannyasyu", label: "威圧感(野手)", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "akkyuuuti", label: "悪球打ち", css_class: "pawa-checkbox-gb", text_class: "pawa-text-good-bad" },
      { id: "error", label: "エラー", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "omaturiotoko", label: "お祭り男", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "cututi", label: "カット打ち", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kyuuti", label: "窮地〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "heatup", label: "ヒートアップ", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "kessyuouda", label: "決勝打", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "konnsinnnokessyouda", label: "渾身の決勝打", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "kousokucharge", label: "高速チャージ", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "sayonaraotokoannda", label: "サヨナラ男(安打)", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "sayonaraotokohonnruida", label: "サヨナラ男(本塁打)", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "dennsetunosayonaraotoko", label: "伝説のサヨナラ男", css_class: "pawa-checkbox-sp",
        text_class: "pawa-text-special" },
      { id: "taistraight", label: "対ストレート〇", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "heisatu", label: "併殺", css_class: "pawa-checkbox-b", text_class: "pawa-text-bad" },
      { id: "headsliding", label: "ヘッドスライディング", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kihakuhead", label: "気迫ヘッド", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "homesisyu", label: "ホーム死守", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "terunokabe", label: "鉄の壁", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "mulchdann", label: "マルチ弾", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "mannruiotokoannda", label: "満塁男(安打)", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "mannruiotokohonnruida", label: "満塁男(本塁打)", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kyoufunomannruiotoko", label: "恐怖の満塁男", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "revenge", label: "リベンジ", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "gyakusyuu", label: "逆襲", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "laserbeam", label: "レーザービーム", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "kousokulaser", label: "高速レーザー", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "haruotoko", label: "春男", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "natuotoko", label: "夏男", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" },
      { id: "akiotoko", label: "秋男", css_class: "pawa-checkbox-g", text_class: "pawa-text-good" }
    ]
  end

  def other_special_abilities
    [
      { id: "meettayou", label: "ミート多用", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "kyousinntayou", label: "強振多用", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "sekkyokudahou", label: "積極打法", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "sinntyoudahou", label: "慎重打法", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "sekkyokutourui", label: "積極盗塁", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "sinntyoutourui", label: "慎重盗塁", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "sekkyokusyubi", label: "積極守備", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "sekkyokusourui", label: "積極走塁", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "sennkyuugann", label: "選球眼", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "sokyuutyuusinn", label: "速球中心", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "hennkakyuutyuusinn", label: "変化球中心", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "teamplaymaru", label: "チームプレイ〇", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "teamplaybatu", label: "チームプレイ✕", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "tyousianntei", label: "調子安定", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "tyousikyokutann", label: "調子極端", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "tetuwann", label: "鉄腕", css_class: "pawa-checkbox-sp", text_class: "pawa-text-special" },
      { id: "tempo", label: "テンポ〇", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "tousyuitihidari", label: "投手位置左", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "tousyuitimigi", label: "投手位置右", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "ninnkimono", label: "人気者", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" },
      { id: "furusyutujyou", label: "フル出場", css_class: "pawa-checkbox-sb", text_class: "pawa-text-sub" }
    ]
  end
end
