gold_or_very_red_abilities:
  回復:
    4: ガソリンタンク
  ケガしにくさ:
    4: 鉄人
  対ピンチ:
    4: 強心臓
    -4: ノミの心臓
  対左打者:
    4: 左キラー
  打たれ強さ:
    4: 不屈の魂
    -4: ガラスのハート
  ノビ:
    4: 怪童
  クイック:
    4: 走者釘付
  チャンス:
    4: 勝負師
  対左投手:
    4: 左腕キラー
  キャッチャー:
    4: 球界の頭脳
  盗塁:
    4: 電光石火
  走塁:
    4: 高速ベースラン
  送球:
    4: ストライク送球